name=ArduinoJson
version=7.4.3
author=Benoit Blanchon
maintainer=Benoit Blanchon
sentence=A simple and efficient JSON library for embedded C++.
paragraph=Vendored single-header release.
category=Data Processing
url=https://arduinojson.org/
architectures=*
